### ISSUE TITLE
Convert view to Django generic view.

### ISSUE THREAD

**Issue by kwangsensei** [KwangSensei/Fiction-Fans#16]
Convert normal view function to Django generic view classes.

**Comment by chinapat317** [comment]
I change it in ChapterView class you should check it if any problem please call me.

**Comment by kwangsensei** [comment]
Cannot run server with that view.
Please fix URL path too.

**Comment by chinapat317** [comment]
@KwangSensei send runserver pic in discord pls.

**Comment by chinapat317** [comment]
![image](https://user-images.githubusercontent.com/78128703/200613548-88235ba5-6970-4211-bdfa-9b024480c0ee.png)
it can run in my laptop.

**Comment by kwangsensei** [comment]
Please finish fixing all views and push it again.

**Comment by kwangsensei** [comment]
Tested.
