### ISSUE TITLE
Authorization bypass & server error

### ISSUE THREAD

**Issue by jbrucker** [KwangSensei/Fiction-Fans#54]
If I do **not** login and go to: https://fictionfans.azurewebsites.net/fiction/1/
I see several links that I can use. 

If I go to https://fictionfans.azurewebsites.net/fiction/2/
then I get a "500 Server Error" screen.

These are reproducible.

**Comment by kwangsensei** [comment]
The reason you get *500 Server Error* when go to https://fictionfans.azurewebsites.net/fiction/2/ because now we have only 1 fiction (https://fictionfans.azurewebsites.net/fiction/1/) on the website. Thank you.

**Comment by chinapat317** [comment]
> The reason you get _500 Server Error_ when go to https://fictionfans.azurewebsites.net/fiction/2/ because now we have only 1 fiction (https://fictionfans.azurewebsites.net/fiction/1/) on the website. Thank you.

We will check it right away. Because it should raise 404 and we will overwrite it to redirect to homepage instead.

**Comment by kwangsensei** [comment]
We have updated our domain to *https://fictionfans.pythonanywhere.com/fiction/*. Now the user has not login can be only read mode.
